name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      commit_time: ${{ steps.prepare.outputs.COMMIT_TIMESTAMP }}
      registry_image: ${{ steps.prepare.outputs.REGISTRY_IMAGE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare various metadata
        id: prepare
        run: |
          # Get the commit timestamp
          export "COMMIT_TIMESTAMP=$(git log -1 --pretty=%ct)"
          echo "COMMIT_TIMESTAMP=${COMMIT_TIMESTAMP}" >> $GITHUB_OUTPUT

          # Lowercase the repository name
          REPO="${{ github.event.pull_request.head.repo.full_name }}" # only populated on PRs
          if [[ -z "${REPO}" ]]; then
            REPO="${{ github.repository }}"
          fi
          UNSANITIZED_REGISTRY_IMAGE="ghcr.io/${REPO}/indev"
          echo "REGISTRY_IMAGE=${UNSANITIZED_REGISTRY_IMAGE,,}" >> $GITHUB_OUTPUT

          # Print it for our audience
          cat $GITHUB_OUTPUT


  build-minrobot:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            platform: amd64
          - runs-on: ubuntu-24.04-arm
            platform: arm64
    runs-on: ${{ matrix.runs-on }}
    needs:
      - prepare
    permissions:
      contents: read
      packages: write
    env:
      SOURCE_DATE_EPOCH: ${{ needs.prepare.outputs.commit_time }}
      REGISTRY_IMAGE: ${{ needs.prepare.outputs.registry_image }}
    outputs:
      # So we can `FROM` this image in the next build
      amd64_digest: ${{ steps.set_digest.outputs.amd64 }}
      arm64_digest: ${{ steps.set_digest.outputs.arm64 }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            # commit sha
            type=sha,prefix=,suffix=-${{ matrix.platform }},format=long

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.platform }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
          file: docker/moos-ivp/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ (github.ref_name == 'main') || (github.repository_owner != 'moos-ivp') }}

      - name: Set digest output
        id: set_digest
        run: echo "${{ matrix.platform }}=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  build-gui:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            platform: amd64
          - runs-on: ubuntu-24.04-arm
            platform: arm64
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
      packages: write
    needs:
      - prepare
    env:
      FLAVOR: "-gui"
      SOURCE_DATE_EPOCH: ${{ needs.prepare.outputs.commit_time }}
      REGISTRY_IMAGE: ${{ needs.prepare.outputs.registry_image }}
    outputs:
      amd64_digest: ${{ steps.set_digest.outputs.amd64 }}
      arm64_digest: ${{ steps.set_digest.outputs.arm64 }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            # commit sha
            type=sha,prefix=,suffix=${{ env.FLAVOR }}-${{ matrix.platform }},format=long

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.platform }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
          file: docker/moos-ivp-gui/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ (github.ref_name == 'main') || (github.repository_owner != 'moos-ivp') }}

      - name: Set digest output
        id: set_digest
        run: echo "${{ matrix.platform }}=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  push-to-registry:
    runs-on: ubuntu-latest
    # Only push images on forks or the main branch
    if: ${{ (github.ref_name == 'main') || (github.repository_owner != 'moos-ivp') }}
    needs:
      - prepare
      - build-minrobot
      - build-gui
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY_IMAGE: ${{ needs.prepare.outputs.registry_image }}
    strategy:
      fail-fast: false
      matrix:
        registry: [docker.io, quay.io, ghcr.io]
    steps:
      - name: Sanitize some things
        id: prepare
        run: |
          # Sanitize org and repo names
          ORG="${{ github.repository_owner }}"
          if [[ ${{ matrix.registry }} != "ghcr.io" ]]; then
            # Quay & DockerHub don't support dashes in the repository name
            ORG="${ORG//\-/}" # Remove dashes from the repository name
          fi

          REPO="${ORG}/${{ github.event.repository.name }}"
          REPO="${REPO,,}" # lowercase

          echo "REPOSITORY=${{ matrix.registry }}/${REPO}" | tee -a $GITHUB_OUTPUT

          # Sanitize the registry name for use by secrets
          REGISTRY="${{ matrix.registry }}"
          REGISTRY="${REGISTRY//[^A-Za-z0-9]/_}" # replace non-alphanumeric with _
          echo "REGISTRY=${REGISTRY}" | tee -a $GITHUB_OUTPUT

      - name: Prepare Credentials
        id: credentials
        run: |
          if [[ ${{ matrix.registry }} == "ghcr.io" ]]; then
            REGISTRY_USERNAME="${{ github.actor }}"
            REGISTRY_PASSWORD="${{ secrets.GITHUB_TOKEN }}"
          else
            # Write the username and password to job outputs
            REGISTRY_USERNAME="${{ secrets[format('REGISTRY_USERNAME_{0}', steps.prepare.outputs.REGISTRY)] }}"
            REGISTRY_PASSWORD="${{ secrets[format('REGISTRY_PASSWORD_{0}', steps.prepare.outputs.REGISTRY)] }}"
          fi

          if [[ -z "${REGISTRY_USERNAME}" && -z "${REGISTRY_PASSWORD}" ]]; then
            # If we don't have the relevant credentials, we can't push. Warn the user, but don't fail.
            echo "::warning::Pushing to ${{ matrix.registry }} is disabled; we can't find credentials"
            echo "REGISTRY_READY=false" | tee -a $GITHUB_OUTPUT
          else
            echo "REGISTRY_USERNAME=${REGISTRY_USERNAME}" >> $GITHUB_OUTPUT
            echo "REGISTRY_PASSWORD=${REGISTRY_PASSWORD}" >> $GITHUB_OUTPUT
            echo "REGISTRY_READY=true" | tee -a $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.prepare.outputs.REPOSITORY }}
          tags: |
            # branch event
            type=ref,enable=true,event=branch
            # tag event
            type=ref,enable=true,event=tag
            # commit sha
            type=sha,prefix=,format=short

      - name: Login to ${{ matrix.registry }}
        uses: docker/login-action@v3
        if: steps.credentials.outputs.REGISTRY_READY == 'true'
        with:
          registry: ${{ matrix.registry }}
          username: ${{ steps.credentials.outputs.REGISTRY_USERNAME }}
          password: ${{ steps.credentials.outputs.REGISTRY_PASSWORD }}

      - name: Push to ${{ matrix.registry }}
        id: check
        if: steps.credentials.outputs.REGISTRY_READY == 'true'
        run: |
          BASE_TAGS=$(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          GUI_TAGS=$(jq -cr '.tags | map("-t " + . + "-gui") | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")

          echo "Base Tags: ${BASE_TAGS}"
          docker buildx imagetools create $BASE_TAGS \
              ${{ env.REGISTRY_IMAGE }}@${{ needs.build-minrobot.outputs.amd64_digest }} \
              ${{ env.REGISTRY_IMAGE }}@${{ needs.build-minrobot.outputs.arm64_digest }}


          echo "GUI Tags: ${GUI_TAGS}"
          docker buildx imagetools create $GUI_TAGS \
              ${{ env.REGISTRY_IMAGE }}@${{ needs.build-gui.outputs.amd64_digest }} \
              ${{ env.REGISTRY_IMAGE }}@${{ needs.build-gui.outputs.arm64_digest }}

